### ISSUE TITLE
Automatically pull ghg-docs repo on server start on GHG hub (same as VEDA hub)

### ISSUE THREAD

**Issue by batpad** [NASA-IMPACT/veda-jupyterhub#7]
Copying this issue over from https://github.com/2i2c-org/infrastructure/issues/3565 as it seems more appropriate to track here.

@yuvipanda says there:

"Via https://github.com/2i2c-org/infrastructure/pull/3124 and follow-up PRs, the NASA VEDA hub automatically clones the [GHG Docs](https://github.com/US-GHG-Center/ghgc-docs) repo each time a user server starts. This behavior is desired for the GHG center hub as well."

@yuvipanda or someone else - could you add a little bit of context of what this does / why we want this?

It seems like there is already work moving toward this - would be good to also have a quick description of what it would mean to have this issue "completed".

**Comment by batpad** [comment]
I see - so this pulls and auto-mounts the `veda-docs` repo using an init container for VEDA hub here: https://github.com/2i2c-org/infrastructure/blob/82e9f0dd0e81be9abe8cb71608e93e3d4f6e6de9/config/clusters/nasa-veda/common.values.yaml#L92C58-L92C99 . This makes the docs and example notebooks available to all users on the hub.

The init container is built here: https://github.com/NASA-IMPACT/veda-jh-environments/tree/main/docker-images/base/nasa-veda-singleuser-init

Am guessing we basically need to copy this pattern over to the GHG cluster config but clone the https://github.com/US-GHG-Center/ghgc-docs repo instead of the `veda-docs` repo.

@ranchodeluxe I think am happy to take this on to get some tangible wins under my belt, unless you really want to.

**Comment by yuvipanda** [comment]
Based on my initial memory trying to get this set up, I think the pattern here (that is common) is that we need something on a hub that will:

1. Pull something via the nbgitpuller commandline `gitpuller`
2. If the pull succeeds, nothing is the issue
3. If the pull fails, writes the logs of the failure to a known log location on the home directory, but otherwise lets the login proceed

The issue we're trying to prevent is the case when setting up the initial repo fails causes the whole server startup to fail. 

So I'd say it would be useful to turn (https://github.com/NASA-IMPACT/veda-jh-environments/blob/main/docker-images/base/nasa-veda-singleuser-init/k8s-init-container-nb-docs.py) into something generic, parameterized in two ways:

1. Various options to the `gitpuller` commandline
2. The target log file location (can default to `~/nbgitpuller.log`)

This allows us to build this in a way that's not specific to ghg nor veda, and allow for configuration knobs to be configurable. In the medium term i'd love for it to be upstreamed into the `nbgitpuller` repo as well.

**Comment by batpad** [comment]
This is done!

When you login to the GHG Center hub now, you should get the `ghgc-docs` repository pulled into your home directory.
